GrowLogWebMVC/Controllers/LocationController.cs
using GrowLog.Models;
using GrowLog.Services;
using GrowLogWebMVC.Data;
using Microsoft.AspNet.Identity;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrowLogWebMVC.Controllers
{
    [Authorize]
    public class LocationController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();
        
        // GET: Location
        public ActionResult Index(int? page)
        {
            var service = CreateLocationService();

            var model = service.GetLocations().OrderBy(m => m.Name);

            int Size_Of_Page = 4;
            int No_Of_Page = (page ?? 1);
            return View(model.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        // GET
        public ActionResult Create()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LocationCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateLocationService();

            if (service.CreateLocation(model))
            {
                TempData["SaveResult"] = "Your location was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Location could not be created.");

            return View(model);
        }

        // GET
        public ActionResult Details(int id)
        {
            var svc = CreateLocationService();
            var model = svc.GetLocationById(id);

            return View(model);
        }

        // GET
        public ActionResult Edit(int id)
        {
            var service = CreateLocationService();
            var detail = service.GetLocationById(id);
            var model =
                new LocationDetail
                {
                    LocationID = detail.LocationID,
                    Name = detail.Name,
                    Description = detail.Description
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, LocationDetail model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.LocationID != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateLocationService();

            if (service.UpdateLocation(model))
            {
                TempData["SaveResult"] = "Your Location was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your Location could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateLocationService();
            var model = svc.GetLocationById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateLocationService();

            service.DeleteLocation(id);

            TempData["SaveResult"] = "Your Location was deleted.";

            return RedirectToAction("Index");
        }




        private LocationService CreateLocationService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new LocationService(userId);
            return service;
        }
    }
}

GrowLogWebMVC/Controllers/LogEntryController.cs
using GrowLog.Models;
using GrowLog.Services;
using GrowLogWebMVC.Data;
using Microsoft.AspNet.Identity;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrowLogWebMVC.Controllers
{
    [Authorize]
    public class LogEntryController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        // GET: LogEntry
        public ActionResult Index(int? plantID, int? page) 
        {

            var service = CreateLogEntryService();
            var model = service.GetLogEntries().Where(le => le.PlantID == plantID
           || plantID == null).OrderBy(m => m.DateCreated);

            int Size_Of_Page = 4;
            int No_Of_Page = (page ?? 1);
            return View(model.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        //GET
        public ActionResult Create()
        {
            ViewBag.PlantId = new SelectList(_db.Plants, "PlantId", "PlantName");
            return View();
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(LogEntryCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateLogEntryService();

            if (service.CreateLogEntry(model))
            {
                TempData["SaveResult"] = "Your Log Entry was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Plant could not be created.");

            return View("model");
        }

        //GET
        public ActionResult Details(int id)
        {
            var svc = CreateLogEntryService();
            var model = svc.GetLogEntriesById(id);

            return View(model);
        }

        //GET
        public ActionResult Edit(int id)
        {
            ViewBag.PlantId = new SelectList(_db.Plants, "PlantId", "PlantName");

            var service = CreateLogEntryService();
            var detail = service.GetLogEntriesById(id);
            var model =
                new LogEntryDetail
                {
                    LogEntryID = detail.LogEntryID,
                    Name = detail.Name,
                    Description = detail.Description,
                    DateCreated = detail.DateCreated,
                    PlantID = detail.PlantID
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, LogEntryDetail model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.LogEntryID != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateLogEntryService();

            if (service.UpdateLogEntry(model))
            {
                TempData["SaveResult"] = "Your Log Entry was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your Log Entry could not be updated.");
            return View(model);
        }

        //GET
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateLogEntryService();
            var model = svc.GetLogEntriesById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateLogEntryService();

            service.DeleteLogEntry(id);

            TempData["SaveResult"] = "Your Log Entry was deleted.";

            return RedirectToAction("Index");
        }







        private LogEntryService CreateLogEntryService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new LogEntryService(userId);
            return service;
        }

    }
}

GrowLogWebMVC/Controllers/PlantController.cs
using GrowLog.Data;
using GrowLog.Models;
using GrowLog.Services;
using GrowLogWebMVC.Data;
using Microsoft.AspNet.Identity;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrowLogWebMVC.Controllers
{
    [Authorize]
    public class PlantController : Controller
    {
        private ApplicationDbContext _db = new ApplicationDbContext();

        // GET: Plant
        public ActionResult Index(string searchBy, string search, int? locationID, int? page) //string SortingOrder, string Filter_Value, 
        {

            var service = CreatePlantService();
            var model = service.GetPlants().Where(p => p.LocationID == locationID 
            || locationID == null);
            

            if (searchBy == "PlantName")
            {
                return View(model.Where(x => x.PlantName.Contains(search) 
                || search == null).ToList().ToPagedList(page ?? 1, 4));
            }
            else if (searchBy == "LocationName")
            {
                return View(model.Where(x => x.LocationName == search 
                || search == null).ToList().ToPagedList(page ?? 1, 4));
            }

            int Size_Of_Page = 4;
            int No_Of_Page = (page ?? 1);
            return View(model.ToPagedList(No_Of_Page, Size_Of_Page));

        }

        // GET
        public ActionResult Create()
        {
            ViewBag.LocationID = new SelectList(_db.Locations, "LocationID", "Name");
            return View();
        }

        // POST 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlantCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreatePlantService();

            if (service.CreatePlant(model))
            {
                TempData["SaveResult"] = "Your plant was created.";
                return RedirectToAction("Index");
            };

            ModelState.AddModelError("", "Plant could not be created.");

            return View("model");
        }

        // GET
        public ActionResult Details(int id)
        {
            var svc = CreatePlantService();
            var model = svc.GetPlantById(id);

            return View(model);
        }

        // GET
        public ActionResult Edit(int id)
        {
            ViewBag.LocationID = new SelectList(_db.Locations, "LocationID", "Name");


            var service = CreatePlantService();
            var detail = service.GetPlantById(id);
            var model =
                new PlantDetail
                {
                    PlantID = detail.PlantID,
                    PlantName = detail.PlantName,
                    Description = detail.Description,
                    PlantingSeasonStart = detail.PlantingSeasonStart,
                    PlantingSeasonEnd = detail.PlantingSeasonEnd,
                    TypeOfPlantCategory = detail.TypeOfPlantCategory,
                    LocationID = detail.LocationID,


                    //HarvestSeasonStart = detail.HarvestSeasonStart,
                    //HarvestSeasonEnd = detail.HarvestSeasonEnd,
                    //FileContent = detail.FileContent,
                    //File = detail.File,
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PlantDetail model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.PlantID != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreatePlantService();

            if (service.UpdatePlant(model))
            {
                TempData["SaveResult"] = "Your Plant was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your Plant could not be updtaed.");
            return View(model);
        }

        //GET
        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreatePlantService();
            var model = svc.GetPlantById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreatePlantService();

            service.DeletePlant(id);

            TempData["SaveResult"] = "Your Plant was deleted.";

            return RedirectToAction("Index");
        }




        private PlantService CreatePlantService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new PlantService(userId);
            return service;
        }
    }
}

GrowLogWebMVC/Views/Plant/Create.cshtml
@model GrowLog.Models.PlantCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Plant", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>PlantCreate</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.PlantName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PlantName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlantName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PlantingSeasonStart, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PlantingSeasonStart, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlantingSeasonStart, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PlantingSeasonEnd, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PlantingSeasonEnd, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlantingSeasonEnd, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LocationID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GrowLogWebMVC/Views/Plant/Delete.cshtml
@model GrowLog.Models.PlantDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PlantDetail</h4>
    <hr />
    <dl class="dl-horizontal">
        @Html.HiddenFor(model => model.OwnerId)
        @Html.HiddenFor(model => model.PlantID)
        @Html.HiddenFor(model => model.LocationID)
        
        <dt>
            @Html.DisplayNameFor(model => model.PlantName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlantName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlantingSeasonStart)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlantingSeasonStart)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PlantingSeasonEnd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlantingSeasonEnd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LocationName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

GrowLogWebMVC/Views/Plant/Details.cshtml
@model GrowLog.Models.PlantDetail

@{
    ViewBag.Title = "Details";
}



<div class="plantDetail content-wrapper" style="width: 50vw; margin: auto;">
    <div class="spacer" style="height: 4.5vw"></div>
    <h2 class="indexTitle" style="color: rgba(255, 255, 255, 0.897); background-color: darkolivegreen; width: 50vw; margin: auto;
      font-family: 'Arbutus', sans-serif; font-size: 6vw; text-align: center; border-style: double;
      border-width: 0.40vw; border-color: darkslategray; border-radius: 7px;">
        @Html.DisplayFor(model => model.PlantName)
    </h2>
    <div class="spacer" style="height: 2vw"></div>


    <div class="detailData" style="color:darkslategray; ">
        <div style="display:flex;">
            <div class="locationName" style="font-family: 'Teko', sans-serif; font-size:4vw; color:darkslategray; width: 25vw;">@Html.DisplayFor(model => model.LocationName)</div>

            <div style="width: 25vw; text-align: end; margin-top: 1.2vw; ">
                <h4>Planting Season</h4>
                <p style="margin-top:-1vw;">
                    @Html.DisplayFor(model => model.PlantingSeasonStart) to @Html.DisplayFor(model => model.PlantingSeasonEnd)
                </p>
            </div>
        </div>

        <hr />
        <div class="dl-horizontal" style="display: flex; width: 50vw; height: 15vw;">

            @Html.HiddenFor(model => model.PlantID)
            @Html.HiddenFor(model => model.LocationID)
            @Html.HiddenFor(model => model.PlantName)
            @Html.HiddenFor(model => model.LocationName)


            @Html.DisplayFor(model => model.Description)


        </div>



    </div>
    <p>
        @Html.ActionLink($"{Model.PlantName} Log Entries", "Index", "LogEntry", null, new { plantID = Model.PlantID, @style = "color:darkslategrey;" }) ||
        @Html.ActionLink("Add Log Entry", "Create", "LogEntry", null, new { @class = "link ", style = "color: darkslategrey;" }) ||
        @Html.ActionLink($"Edit {Model.PlantName}", "Edit", new { id = Model.PlantID }, htmlAttributes: new { @class = "link", @style = "color: darkslategrey;" }) ||
        @Html.ActionLink("Plant List", "Index", null, htmlAttributes: new { @class = "link", @style = "color: darkslategrey;" }) ||
        @Html.ActionLink("Location List", "Index", "Location", null, new { @class = "link ", style = "color: darkslategrey;" })
    </p>
    <style>
        .img-fluid {
            height: 50vh;
            width: 50vw;
        }
    </style>
</div>

GrowLogWebMVC/Views/Plant/Edit.cshtml
@model GrowLog.Models.PlantDetail

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>PlantDetail</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.PlantID)

    <div class="form-group">
        @Html.LabelFor(model => model.PlantName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PlantName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlantName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PlantingSeasonStart, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PlantingSeasonStart, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlantingSeasonStart, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PlantingSeasonEnd, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PlantingSeasonEnd, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PlantingSeasonEnd, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.Location.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Location.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

GrowLogWebMVC/Views/Plant/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@using GrowLog.Models;
@model IPagedList<PlantListItem>

<link href="~/Content/PagedList.css" rel="stylesheet" />

@{
    ViewBag.Title = "Plants";
}

<div class="content-wrapper" style="width: 50vw; margin: auto;">
    <div class="spacer" style="height: 4.5vw"></div>
    <h2 class="indexTitle" style="color: rgba(255, 255, 255, 0.897); background-color: darkolivegreen; width: 50vw; margin: auto; 
      font-family: 'Arbutus', sans-serif; font-size: 6vw; text-align: center; border-style: double; 
      border-width: 0.40vw; border-color: darkslategray; border-radius: 7px;">
        Plants
    </h2>
    <div class="spacer" style="height: 2vw"></div>


    <p>
        <div class="searchBar" style="text-align: end;">
            @using (Html.BeginForm("Index", "Plant", FormMethod.Get))
            {
                @Html.RadioButton("searchBy", "PlantName") <text>Name</text>
                @Html.RadioButton("searchBy", "LocationName", true) <text>Location</text> <br />
                <b>Search Plants: </b> @Html.TextBox("search") <input type="submit" value="Search" />
                @Html.ActionLink("Refresh", "Index", "Plant", null, new { @class = "link ", style = "color: darkslategrey;" })
            }
        </div>
        <br /><br />
        <div class="linkBar" style="text-align:end; font-size: 1.5vw;">
            @Html.ActionLink("Create New Plant", "Create", null, new { @class = "link ", style = "color: darkslategrey;" }) ||
            @Html.ActionLink("Location List", "Index", "Location", null, new { @class = "link ", style = "color: darkslategrey;" }) ||
            @Html.ActionLink("Calendar", "Index", "BasicScheduler", null, new { @style = "color: darkslategrey;" })

        </div>
    </p>
    <br />
    <table class="table" style="width:50vw; margin:auto;">


        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="3"> No Plants match search criteria. </td>
            </tr>
        }
        else
        {
            foreach (var item in Model)
            {
                <tr class="plantTableData" style="font-size: 2vw;">

                    <td style="text-align: left;">
                        
                        @Html.ActionLink(item.PlantName, "Details", new { id = item.PlantID }, htmlAttributes: new { @class = "plantNameLink", @style = "color: darkslategrey; font-size: 4vw; text-decoration:none;" })
                        <br />
                        Start Planting: @Html.DisplayFor(modelItem => item.PlantingSeasonStart)
                        <br />
                        Garden: @Html.DisplayFor(modelItem => item.LocationName)
                        <br /><br />
                              <div style="text-align: center; font-size: 1.5vw;">
                                  @Html.ActionLink("Add Log Entry", "Create", "LogEntry", new { plantId = item.PlantID }, htmlAttributes: new { @class = "plantNameLink ", style = "color: darkslategrey; font-size: 1.5vw;  text-decoration:none;" }) ||
                                  @Html.ActionLink($"{item.PlantName} Log Entries", "Index", "LogEntry", new { plantId = item.PlantID }, htmlAttributes: new { @class = "plantNameLink", @style = "color: darkslategrey; font-size: 1.5vw;  text-decoration:none;" }) ||
                                  @Html.ActionLink($"Edit {item.PlantName}", "Edit", new { id = item.PlantID }, htmlAttributes: new { @class = "plantNameLink", @style = "color: darkslategrey; font-size: 1.5vw;  text-decoration:none;" }) ||
                                  @Html.ActionLink("Details", "Details", new { id = item.PlantID }, htmlAttributes: new { @class = "plantNameLink", @style = "color: darkslategrey; font-size: 1.5vw;  text-decoration:none;" }) ||
                                  @Html.ActionLink("Delete", "Delete", new { id = item.PlantID }, htmlAttributes: new { @class = "plantNameLink", @style = "color: darkslategrey; font-size: 1.5vw;  text-decoration:none;" })
                              </div>
                    </td>

                </tr>
            }
        }
    </table>
    <br />
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, searchBy = Request.QueryString["searchBy"], search = Request.QueryString["search"] }),
        new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true, DisplayItemSliceAndTotal = true })

</div>